float32 position_mm
int32 goal_current
int32 profile_velocity
int32 profile_acceleration
float32 timeout_sec
---
bool success
string message
float32 present_position_mm
int32 present_current
bool in_position
bool grasp_detected
dsr_gripper_tcp_interfaces/GripperState state
